//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 09:28:36 PM MSK 
//


package ru.pgu.mq_service.jaxbdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EventObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="eventDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="eventComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eventAuthor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="event"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="orderStatusEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}OrderStatusEvent"/&gt;
 *                   &lt;element name="paymentStatusEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}PaymentStatusEvent"/&gt;
 *                   &lt;element name="infoEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}InfoEvent"/&gt;
 *                   &lt;element name="textMessageEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}TextMessageEvent"/&gt;
 *                   &lt;element name="invitationEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}InvitationEvent"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventObject", propOrder = {
    "orderId",
    "eventDate",
    "eventComment",
    "eventAuthor",
    "event"
})
public class EventObject {

    protected long orderId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventDate;
    protected String eventComment;
    protected String eventAuthor;
    @XmlElement(required = true)
    protected EventObject.Event event;

    /**
     * Gets the value of the orderId property.
     * 
     */
    public long getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     */
    public void setOrderId(long value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the eventDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventDate() {
        return eventDate;
    }

    /**
     * Sets the value of the eventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventDate(XMLGregorianCalendar value) {
        this.eventDate = value;
    }

    /**
     * Gets the value of the eventComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventComment() {
        return eventComment;
    }

    /**
     * Sets the value of the eventComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventComment(String value) {
        this.eventComment = value;
    }

    /**
     * Gets the value of the eventAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventAuthor() {
        return eventAuthor;
    }

    /**
     * Sets the value of the eventAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventAuthor(String value) {
        this.eventAuthor = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link EventObject.Event }
     *     
     */
    public EventObject.Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventObject.Event }
     *     
     */
    public void setEvent(EventObject.Event value) {
        this.event = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="orderStatusEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}OrderStatusEvent"/&gt;
     *         &lt;element name="paymentStatusEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}PaymentStatusEvent"/&gt;
     *         &lt;element name="infoEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}InfoEvent"/&gt;
     *         &lt;element name="textMessageEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}TextMessageEvent"/&gt;
     *         &lt;element name="invitationEvent" type="{http://epgu.gosuslugi.ru/lk/order/event/SCVDEV/3.1.0}InvitationEvent"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderStatusEvent",
        "paymentStatusEvent",
        "infoEvent",
        "textMessageEvent",
        "invitationEvent"
    })
    public static class Event {

        protected OrderStatusEvent orderStatusEvent;
        protected PaymentStatusEvent paymentStatusEvent;
        protected InfoEvent infoEvent;
        protected TextMessageEvent textMessageEvent;
        protected InvitationEvent invitationEvent;

        /**
         * Gets the value of the orderStatusEvent property.
         * 
         * @return
         *     possible object is
         *     {@link OrderStatusEvent }
         *     
         */
        public OrderStatusEvent getOrderStatusEvent() {
            return orderStatusEvent;
        }

        /**
         * Sets the value of the orderStatusEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderStatusEvent }
         *     
         */
        public void setOrderStatusEvent(OrderStatusEvent value) {
            this.orderStatusEvent = value;
        }

        /**
         * Gets the value of the paymentStatusEvent property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentStatusEvent }
         *     
         */
        public PaymentStatusEvent getPaymentStatusEvent() {
            return paymentStatusEvent;
        }

        /**
         * Sets the value of the paymentStatusEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentStatusEvent }
         *     
         */
        public void setPaymentStatusEvent(PaymentStatusEvent value) {
            this.paymentStatusEvent = value;
        }

        /**
         * Gets the value of the infoEvent property.
         * 
         * @return
         *     possible object is
         *     {@link InfoEvent }
         *     
         */
        public InfoEvent getInfoEvent() {
            return infoEvent;
        }

        /**
         * Sets the value of the infoEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link InfoEvent }
         *     
         */
        public void setInfoEvent(InfoEvent value) {
            this.infoEvent = value;
        }

        /**
         * Gets the value of the textMessageEvent property.
         * 
         * @return
         *     possible object is
         *     {@link TextMessageEvent }
         *     
         */
        public TextMessageEvent getTextMessageEvent() {
            return textMessageEvent;
        }

        /**
         * Sets the value of the textMessageEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextMessageEvent }
         *     
         */
        public void setTextMessageEvent(TextMessageEvent value) {
            this.textMessageEvent = value;
        }

        /**
         * Gets the value of the invitationEvent property.
         * 
         * @return
         *     possible object is
         *     {@link InvitationEvent }
         *     
         */
        public InvitationEvent getInvitationEvent() {
            return invitationEvent;
        }

        /**
         * Sets the value of the invitationEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvitationEvent }
         *     
         */
        public void setInvitationEvent(InvitationEvent value) {
            this.invitationEvent = value;
        }

    }

}
